//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotGrounded {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotGrounded() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.plotters.PlotGrounded", typeof(PlotGrounded).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearing ship departure distance.
        /// </summary>
        internal static string NearingShipDistance {
            get {
                return ResourceManager.GetString("NearingShipDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan one:.
        /// </summary>
        internal static string ScanOne_Long {
            get {
                return ResourceManager.GetString("ScanOne_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st:.
        /// </summary>
        internal static string ScanOne_Short {
            get {
                return ResourceManager.GetString("ScanOne_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan one: invalid.
        /// </summary>
        internal static string ScanOneInvalid {
            get {
                return ResourceManager.GetString("ScanOneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan two:.
        /// </summary>
        internal static string ScanTwo_Long {
            get {
                return ResourceManager.GetString("ScanTwo_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd:.
        /// </summary>
        internal static string ScanTwo_Short {
            get {
                return ResourceManager.GetString("ScanTwo_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan two: invalid.
        /// </summary>
        internal static string ScanTwoInvalid {
            get {
                return ResourceManager.GetString("ScanTwoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship:.
        /// </summary>
        internal static string Ship {
            get {
                return ResourceManager.GetString("Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRV:.
        /// </summary>
        internal static string SRV {
            get {
                return ResourceManager.GetString("SRV", resourceCulture);
            }
        }
    }
}
