//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotGuardianStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotGuardianStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.plotters.PlotGuardianStatus", typeof(PlotGuardianStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align with site origin and rise to target altitude: {0}m.
        /// </summary>
        internal static string AlignAndRise {
            get {
                return ResourceManager.GetString("AlignAndRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align with buttress.
        /// </summary>
        internal static string AlignWithButtress {
            get {
                return ResourceManager.GetString("AlignWithButtress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        internal static string ChooseAbsent {
            get {
                return ResourceManager.GetString("ChooseAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string ChooseEmpty {
            get {
                return ResourceManager.GetString("ChooseEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        internal static string ChoosePresent {
            get {
                return ResourceManager.GetString("ChoosePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active obelisk groups: {0}.
        /// </summary>
        internal static string FooterActiveObeliskGroups {
            get {
                return ResourceManager.GetString("FooterActiveObeliskGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (toggle cockpit mode once to set).
        /// </summary>
        internal static string FooterToggleModeOnce {
            get {
                return ResourceManager.GetString("FooterToggleModeOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (toggle cockpit mode twice to set).
        /// </summary>
        internal static string FooterToggleModeTwice {
            get {
                return ResourceManager.GetString("FooterToggleModeTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site type unknown.
        /// </summary>
        internal static string HeaderUnknownSiteType {
            get {
                return ResourceManager.GetString("HeaderUnknownSiteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log has been acquired.
        /// </summary>
        internal static string LineRamTahAcquired {
            get {
                return ResourceManager.GetString("LineRamTahAcquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needed for Ram Tah mission.
        /// </summary>
        internal static string LineRamTahNeeded {
            get {
                return ResourceManager.GetString("LineRamTahNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guardian mats full - toggle cockpit mode again to mark scanned).
        /// </summary>
        internal static string MatsFullOne {
            get {
                return ResourceManager.GetString("MatsFullOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guardian mats full - toggle cockpit mode twice to mark scanned).
        /// </summary>
        internal static string MatsFullTwo {
            get {
                return ResourceManager.GetString("MatsFullTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obelisk {0}: {1}.
        /// </summary>
        internal static string NearObeliskHeader {
            get {
                return ResourceManager.GetString("NearObeliskHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move within ~75m to inspect an item.
        /// </summary>
        internal static string NoNearPoiHeader {
            get {
                return ResourceManager.GetString("NoNearPoiHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ObeliskActive {
            get {
                return ResourceManager.GetString("ObeliskActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken.
        /// </summary>
        internal static string ObeliskBroken {
            get {
                return ResourceManager.GetString("ObeliskBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string ObeliskInactive {
            get {
                return ResourceManager.GetString("ObeliskInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( Don&apos;t forget to set 3 fire groups in ships and SRVs ).
        /// </summary>
        internal static string OnApproachFooter {
            get {
                return ResourceManager.GetString("OnApproachFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approaching Guardian Ruins ....
        /// </summary>
        internal static string OnApproachHeaderRuins {
            get {
                return ResourceManager.GetString("OnApproachHeaderRuins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approaching Guardian Structure ....
        /// </summary>
        internal static string OnApproachHeaderStructure {
            get {
                return ResourceManager.GetString("OnApproachHeaderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruins #{0} - {1}.
        /// </summary>
        internal static string OnApproachMiddleRuins {
            get {
                return ResourceManager.GetString("OnApproachMiddleRuins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - blue print: {1}.
        /// </summary>
        internal static string OnApproachMiddleStructure {
            get {
                return ResourceManager.GetString("OnApproachMiddleStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - no blue print.
        /// </summary>
        internal static string OnApproachMiddleStructureNoBluePrint {
            get {
                return ResourceManager.GetString("OnApproachMiddleStructureNoBluePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face the side with a single large left facing triangle..
        /// </summary>
        internal static string RelicTowerFaceHint {
            get {
                return ResourceManager.GetString("RelicTowerFaceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (toggle weapon to force location update).
        /// </summary>
        internal static string RelicTowerFootHint {
            get {
                return ResourceManager.GetString("RelicTowerFootHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded heading: {0}°.
        /// </summary>
        internal static string RelicTowerHeadingKnown {
            get {
                return ResourceManager.GetString("RelicTowerHeadingKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Profile Analyser near Relic Towers for aiming assistance.
        ///Face the side with a single large left facing triangle..
        /// </summary>
        internal static string RelicTowerNonToolHint {
            get {
                return ResourceManager.GetString("RelicTowerNonToolHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires:.
        /// </summary>
        internal static string RequiresPrefix {
            get {
                return ResourceManager.GetString("RequiresPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for {0}.
        /// </summary>
        internal static string RequiresSuffix {
            get {
                return ResourceManager.GetString("RequiresSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (toggle lights to force update).
        /// </summary>
        internal static string ToggleLightsUpdateHint {
            get {
                return ResourceManager.GetString("ToggleLightsUpdateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle shields to set Relic Tower heading..
        /// </summary>
        internal static string ToggleShieldsForRelicTower {
            get {
                return ResourceManager.GetString("ToggleShieldsForRelicTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not scanned this obelisk.
        /// </summary>
        internal static string YouHaveNotScanned {
            get {
                return ResourceManager.GetString("YouHaveNotScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have scanned this obelisk.
        /// </summary>
        internal static string YouHaveScanned {
            get {
                return ResourceManager.GetString("YouHaveScanned", resourceCulture);
            }
        }
    }
}
