//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotGuardians {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotGuardians() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.plotters.PlotGuardians", typeof(PlotGuardians).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey: {0} | {1}/{2} relics, {3}/{4} items.
        /// </summary>
        internal static string HeaderGeneral {
            get {
                return ResourceManager.GetString("HeaderGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Relic Tower heading.
        /// </summary>
        internal static string HeaderNeedRelicTowerHeading {
            get {
                return ResourceManager.GetString("HeaderNeedRelicTowerHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need {0} Relic Tower heading.
        /// </summary>
        internal static string HeaderNeedRelicTowers {
            get {
                return ResourceManager.GetString("HeaderNeedRelicTowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruins #{0}: survey complete.
        /// </summary>
        internal static string HeaderRuinsComplete {
            get {
                return ResourceManager.GetString("HeaderRuinsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure {0}: survey complete.
        /// </summary>
        internal static string HeaderStructureComplete {
            get {
                return ResourceManager.GetString("HeaderStructureComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to site: {0}°.
        /// </summary>
        internal static string HeadingSite {
            get {
                return ResourceManager.GetString("HeadingSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown heading.
        /// </summary>
        internal static string HeadingUnknown {
            get {
                return ResourceManager.GetString("HeadingUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ■ Note: there is no map yet for: {0}.
        /// </summary>
        internal static string IdentifyNoMap {
            get {
                return ResourceManager.GetString("IdentifyNoMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need site heading:
        ///
        ///■ To use current heading either:
        ///    - Toggle cockpit mode twice
        ///    - Send message:   .heading
        ///
        ///■ Or send message: &lt;degrees&gt;.
        /// </summary>
        internal static string IdentifySiteHeading {
            get {
                return ResourceManager.GetString("IdentifySiteHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select site type with
        ///fire group or send
        ///message:
        ///
        /// &apos;a&apos; for {0}
        ///
        /// &apos;b&apos; for {1}
        ///
        /// &apos;g&apos; for {2}.
        /// </summary>
        internal static string IdentifySiteType {
            get {
                return ResourceManager.GetString("IdentifySiteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align with this buttress:.
        /// </summary>
        internal static string IdentifyWithButtress {
            get {
                return ResourceManager.GetString("IdentifyWithButtress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align with the data port:.
        /// </summary>
        internal static string IdentifyWithPort {
            get {
                return ResourceManager.GetString("IdentifyWithPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (There is no map yet for: {0}).
        /// </summary>
        internal static string NoMapForType {
            get {
                return ResourceManager.GetString("NoMapForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obelisk {0} - dist: {1}.
        /// </summary>
        internal static string ObliskFooter {
            get {
                return ResourceManager.GetString("ObliskFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Ruins #{1} - {2}.
        /// </summary>
        internal static string RuinsFooter {
            get {
                return ResourceManager.GetString("RuinsFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string StructureFooter {
            get {
                return ResourceManager.GetString("StructureFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string TrackLeft {
            get {
                return ResourceManager.GetString("TrackLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude: {0}m | Target altitude: {1}m.
        /// </summary>
        internal static string TrackOriginFooter {
            get {
                return ResourceManager.GetString("TrackOriginFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site heading: {0}°.
        /// </summary>
        internal static string TrackOriginHeaderPrefix {
            get {
                return ResourceManager.GetString("TrackOriginHeaderPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate ship {0} {1}°.
        /// </summary>
        internal static string TrackOriginHeaderSuffix {
            get {
                return ResourceManager.GetString("TrackOriginHeaderSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string TrackRight {
            get {
                return ResourceManager.GetString("TrackRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom: {0}.
        /// </summary>
        internal static string ZoomLevel {
            get {
                return ResourceManager.GetString("ZoomLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (auto).
        /// </summary>
        internal static string ZoomLevelAuto {
            get {
                return ResourceManager.GetString("ZoomLevelAuto", resourceCulture);
            }
        }
    }
}
