//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotSysStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotSysStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.plotters.PlotSysStatus", typeof(PlotSysStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | {0}x Bio signals on: .
        /// </summary>
        internal static string BioSignals {
            get {
                return ResourceManager.GetString("BioSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}x bodies: .
        /// </summary>
        internal static string DssRemaining {
            get {
                return ResourceManager.GetString("DssRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSS {0}% complete.
        /// </summary>
        internal static string FssCompleteLong {
            get {
                return ResourceManager.GetString("FssCompleteLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSS {0}%.
        /// </summary>
        internal static string FssCompleteShort {
            get {
                return ResourceManager.GetString("FssCompleteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSS not started.
        /// </summary>
        internal static string FssNotStarted {
            get {
                return ResourceManager.GetString("FssNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSS survey: .
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next system:.
        /// </summary>
        internal static string NextSystem {
            get {
                return ResourceManager.GetString("NextSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoDssMeet {
            get {
                return ResourceManager.GetString("NoDssMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ► {0} non-body signals.
        /// </summary>
        internal static string NonBodySignals {
            get {
                return ResourceManager.GetString("NonBodySignals", resourceCulture);
            }
        }
    }
}
