//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotBodyInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotBodyInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.plotters.PlotBodyInfo", typeof(PlotBodyInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmosphere:.
        /// </summary>
        internal static string Atmosphere {
            get {
                return ResourceManager.GetString("Atmosphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio signals: {0} ( value: {1} cr ).
        /// </summary>
        internal static string BioSignals {
            get {
                return ResourceManager.GetString("BioSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth Like.
        /// </summary>
        internal static string EarthLike {
            get {
                return ResourceManager.GetString("EarthLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First mapped.
        /// </summary>
        internal static string FirstMapped {
            get {
                return ResourceManager.GetString("FirstMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo signals: {0}.
        /// </summary>
        internal static string GeoSignals {
            get {
                return ResourceManager.GetString("GeoSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity: {0}g.
        /// </summary>
        internal static string Gravity {
            get {
                return ResourceManager.GetString("Gravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials:.
        /// </summary>
        internal static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure: {0}.
        /// </summary>
        internal static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(atm).
        /// </summary>
        internal static string PressureValue {
            get {
                return ResourceManager.GetString("PressureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rings:.
        /// </summary>
        internal static string Rings {
            get {
                return ResourceManager.GetString("Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan required.
        /// </summary>
        internal static string ScanRequired {
            get {
                return ResourceManager.GetString("ScanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan value.
        /// </summary>
        internal static string ScanValue {
            get {
                return ResourceManager.GetString("ScanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class: {0}.
        /// </summary>
        internal static string StarClass {
            get {
                return ResourceManager.GetString("StarClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp: {0}K.
        /// </summary>
        internal static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terraformable.
        /// </summary>
        internal static string Terraformable {
            get {
                return ResourceManager.GetString("Terraformable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undiscovered.
        /// </summary>
        internal static string Undiscovered {
            get {
                return ResourceManager.GetString("Undiscovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmapped.
        /// </summary>
        internal static string Unmapped {
            get {
                return ResourceManager.GetString("Unmapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volcanism:.
        /// </summary>
        internal static string Volcanism {
            get {
                return ResourceManager.GetString("Volcanism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (with DSS: {0}).
        /// </summary>
        internal static string WithDSS {
            get {
                return ResourceManager.GetString("WithDSS", resourceCulture);
            }
        }
    }
}
