//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotHumanSite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotHumanSite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.plotters.PlotHumanSite", typeof(PlotHumanSite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter is active.
        /// </summary>
        internal static string ActiveFighter {
            get {
                return ResourceManager.GetString("ActiveFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGRI.
        /// </summary>
        internal static string AGRI {
            get {
                return ResourceManager.GetString("AGRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto dock in progress.
        /// </summary>
        internal static string AutoDock1 {
            get {
                return ResourceManager.GetString("AutoDock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement auto-identification supported.
        /// </summary>
        internal static string AutoDock2 {
            get {
                return ResourceManager.GetString("AutoDock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not switch to external camera.
        /// </summary>
        internal static string AutoDock3 {
            get {
                return ResourceManager.GetString("AutoDock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMD.
        /// </summary>
        internal static string CMD {
            get {
                return ResourceManager.GetString("CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too far away.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docking approved: pad #{0}.
        /// </summary>
        internal static string DockingApproved {
            get {
                return ResourceManager.GetString("DockingApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docking denied.
        /// </summary>
        internal static string DockingDenied {
            get {
                return ResourceManager.GetString("DockingDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docking requested.
        /// </summary>
        internal static string DockingRequested {
            get {
                return ResourceManager.GetString("DockingRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXT.
        /// </summary>
        internal static string EXT {
            get {
                return ResourceManager.GetString("EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction.
        /// </summary>
        internal static string Faction {
            get {
                return ResourceManager.GetString("Faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government.
        /// </summary>
        internal static string Government {
            get {
                return ResourceManager.GetString("Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAB.
        /// </summary>
        internal static string HAB {
            get {
                return ResourceManager.GetString("HAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interstellar Factors available.
        /// </summary>
        internal static string HasInterstellar {
            get {
                return ResourceManager.GetString("HasInterstellar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To manually identify:.
        /// </summary>
        internal static string HelpFoot0 {
            get {
                return ResourceManager.GetString("HelpFoot0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Walk to the center of any landing pad and crouch.
        /// </summary>
        internal static string HelpFoot1 {
            get {
                return ResourceManager.GetString("HelpFoot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Place your left foot over the the center grooves.
        /// </summary>
        internal static string HelpFoot2 {
            get {
                return ResourceManager.GetString("HelpFoot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Face with the chevrons ahead to your left.
        /// </summary>
        internal static string HelpFoot3 {
            get {
                return ResourceManager.GetString("HelpFoot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Aim at the end of the groove ahead of you.
        /// </summary>
        internal static string HelpFoot4 {
            get {
                return ResourceManager.GetString("HelpFoot4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Send message &apos;{0}&apos;.
        /// </summary>
        internal static string HelpFoot5 {
            get {
                return ResourceManager.GetString("HelpFoot5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the wiki for more info.
        /// </summary>
        internal static string HelpFoot6 {
            get {
                return ResourceManager.GetString("HelpFoot6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement will be identified after next action.
        /// </summary>
        internal static string HelpShip1 {
            get {
                return ResourceManager.GetString("HelpShip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To manually identify.
        /// </summary>
        internal static string HelpShip2 {
            get {
                return ResourceManager.GetString("HelpShip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send &apos;{0}&apos; when docked.
        /// </summary>
        internal static string HelpShip3 {
            get {
                return ResourceManager.GetString("HelpShip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostile.
        /// </summary>
        internal static string Hostile {
            get {
                return ResourceManager.GetString("Hostile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IND.
        /// </summary>
        internal static string IND {
            get {
                return ResourceManager.GetString("IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Influence.
        /// </summary>
        internal static string Influence {
            get {
                return ResourceManager.GetString("Influence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known settlement.
        /// </summary>
        internal static string KnownSettlement {
            get {
                return ResourceManager.GetString("KnownSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAB.
        /// </summary>
        internal static string LAB {
            get {
                return ResourceManager.GetString("LAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual docking in progress.
        /// </summary>
        internal static string ManualDock1 {
            get {
                return ResourceManager.GetString("ManualDock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement identification will be delayed.
        /// </summary>
        internal static string ManualDock2 {
            get {
                return ResourceManager.GetString("ManualDock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto dock recommended.
        /// </summary>
        internal static string ManualDock3 {
            get {
                return ResourceManager.GetString("ManualDock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MED.
        /// </summary>
        internal static string MED {
            get {
                return ResourceManager.GetString("MED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pads available.
        /// </summary>
        internal static string NoSpace {
            get {
                return ResourceManager.GetString("NoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offenses.
        /// </summary>
        internal static string Offenses {
            get {
                return ResourceManager.GetString("Offenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On approach.
        /// </summary>
        internal static string OnApproach {
            get {
                return ResourceManager.GetString("OnApproach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POW.
        /// </summary>
        internal static string POW {
            get {
                return ResourceManager.GetString("POW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWR.
        /// </summary>
        internal static string PWR {
            get {
                return ResourceManager.GetString("PWR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES.
        /// </summary>
        internal static string RES {
            get {
                return ResourceManager.GetString("RES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STO.
        /// </summary>
        internal static string STO {
            get {
                return ResourceManager.GetString("STO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship too large.
        /// </summary>
        internal static string TooLarge {
            get {
                return ResourceManager.GetString("TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown settlement type and heading.
        /// </summary>
        internal static string UnknownTypeHeading {
            get {
                return ResourceManager.GetString("UnknownTypeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown settlement heading.
        /// </summary>
        internal static string UnkownHeading {
            get {
                return ResourceManager.GetString("UnkownHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reputation: {0}.
        /// </summary>
        internal static string YourRep {
            get {
                return ResourceManager.GetString("YourRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom: {0}.
        /// </summary>
        internal static string ZoomHeader {
            get {
                return ResourceManager.GetString("ZoomHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom: {0} (Auto).
        /// </summary>
        internal static string ZoomHeaderAuto {
            get {
                return ResourceManager.GetString("ZoomHeaderAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z: {0}.
        /// </summary>
        internal static string ZoomHeaderMin {
            get {
                return ResourceManager.GetString("ZoomHeaderMin", resourceCulture);
            }
        }
    }
}
