//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotBioSystem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotBioSystem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.plotters.PlotBioSystem", typeof(PlotBioSystem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body {0} bio signals: {1}.
        /// </summary>
        internal static string BodyBio_Header {
            get {
                return ResourceManager.GetString("BodyBio_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSS required.
        /// </summary>
        internal static string DssRequired {
            get {
                return ResourceManager.GetString("DssRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (FF bonus: {0}).
        /// </summary>
        internal static string FFBonus {
            get {
                return ResourceManager.GetString("FFBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System FSS required.
        /// </summary>
        internal static string FssRequired {
            get {
                return ResourceManager.GetString("FssRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo signals: {0}.
        /// </summary>
        internal static string GeoSignals {
            get {
                return ResourceManager.GetString("GeoSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not predicted!.
        /// </summary>
        internal static string NotPredicted {
            get {
                return ResourceManager.GetString("NotPredicted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards: {0}.
        /// </summary>
        internal static string RewardFooter {
            get {
                return ResourceManager.GetString("RewardFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio signals: {0}.
        /// </summary>
        internal static string SysBio_Header {
            get {
                return ResourceManager.GetString("SysBio_Header", resourceCulture);
            }
        }
    }
}
