//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotFSSInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotFSSInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.plotters.PlotFSSInfo", typeof(PlotFSSInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Genus.
        /// </summary>
        internal static string CountGenus {
            get {
                return ResourceManager.GetString("CountGenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Geo.
        /// </summary>
        internal static string CountGeo {
            get {
                return ResourceManager.GetString("CountGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan value | DSS value.
        /// </summary>
        internal static string Footer1 {
            get {
                return ResourceManager.GetString("Footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌎 Terraformable
        ///🚀 Landable ⚑ Undiscovered.
        /// </summary>
        internal static string Footer2 {
            get {
                return ResourceManager.GetString("Footer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( Hiding bodies &lt; {0} ).
        /// </summary>
        internal static string HidingBodies {
            get {
                return ResourceManager.GetString("HidingBodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned all {0} bodies: {1}.
        /// </summary>
        internal static string ScannedAllBodies {
            get {
                return ResourceManager.GetString("ScannedAllBodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned {0} bodies: {1}.
        /// </summary>
        internal static string ScannedBodies {
            get {
                return ResourceManager.GetString("ScannedBodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (scan to populate).
        /// </summary>
        internal static string ScanToPopulate {
            get {
                return ResourceManager.GetString("ScanToPopulate", resourceCulture);
            }
        }
    }
}
