//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotBioStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotBioStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.plotters.PlotBioStatus", typeof(PlotBioStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio signals detected - DSS Scan required.
        /// </summary>
        internal static string DssRequired {
            get {
                return ResourceManager.GetString("DssRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All signals scanned.
        /// </summary>
        internal static string FooterAllScanned {
            get {
                return ResourceManager.GetString("FooterAllScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All signals scanned with FF bonus applied.
        /// </summary>
        internal static string FooterAllScannedFF {
            get {
                return ResourceManager.GetString("FooterAllScannedFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying first footfall bonus.
        /// </summary>
        internal static string FooterApplyFF {
            get {
                return ResourceManager.GetString("FooterApplyFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Composition Scanner to set tracker targets.
        /// </summary>
        internal static string FooterUseCompScanner {
            get {
                return ResourceManager.GetString("FooterUseCompScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo #{0}.
        /// </summary>
        internal static string GeoN {
            get {
                return ResourceManager.GetString("GeoN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biological signals: {0} | Analyzed: {1}.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong. Please share logs..
        /// </summary>
        internal static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (FF bonus).
        /// </summary>
        internal static string SuffixFF {
            get {
                return ResourceManager.GetString("SuffixFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Incomplete {0} scans from {1}.
        /// </summary>
        internal static string WarningStaleScans {
            get {
                return ResourceManager.GetString("WarningStaleScans", resourceCulture);
            }
        }
    }
}
