//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotJumpInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotJumpInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.plotters.PlotJumpInfo", typeof(PlotJumpInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered by {0} {1}.
        /// </summary>
        internal static string DiscoveredBy {
            get {
                return ResourceManager.GetString("DiscoveredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beacon.
        /// </summary>
        internal static string GuardianBeacon {
            get {
                return ResourceManager.GetString("GuardianBeacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruins: {0}.
        /// </summary>
        internal static string GuardianRuins {
            get {
                return ResourceManager.GetString("GuardianRuins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structures: {0}.
        /// </summary>
        internal static string GuardianStructures {
            get {
                return ResourceManager.GetString("GuardianStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0} of {1}.
        /// </summary>
        internal static string JumpCounts {
            get {
                return ResourceManager.GetString("JumpCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}ly.
        /// </summary>
        internal static string JumpDistance {
            get {
                return ResourceManager.GetString("JumpDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated: {0}.
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next jump:.
        /// </summary>
        internal static string NextJump {
            get {
                return ResourceManager.GetString("NextJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian.
        /// </summary>
        internal static string SpecialGuardian {
            get {
                return ResourceManager.GetString("SpecialGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0} of {1}.
        /// </summary>
        internal static string SpecialHopInfo {
            get {
                return ResourceManager.GetString("SpecialHopInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string SpecialJoiner {
            get {
                return ResourceManager.GetString("SpecialJoiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now entering.
        /// </summary>
        internal static string SpecialNowEntering {
            get {
                return ResourceManager.GetString("SpecialNowEntering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route hop.
        /// </summary>
        internal static string SpecialRouteHop {
            get {
                return ResourceManager.GetString("SpecialRouteHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class: {0}.
        /// </summary>
        internal static string StarClass {
            get {
                return ResourceManager.GetString("StarClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic last 24 hours: {0}, week: {1}, ever: {2}.
        /// </summary>
        internal static string TrafficInfo {
            get {
                return ResourceManager.GetString("TrafficInfo", resourceCulture);
            }
        }
    }
}
