//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrvSurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Codex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Codex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.Properties.Codex", typeof(Codex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aleoida.
        /// </summary>
        internal static string Aleoida {
            get {
                return ResourceManager.GetString("Aleoida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amethyst.
        /// </summary>
        internal static string Amethyst {
            get {
                return ResourceManager.GetString("Amethyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amphora Plant.
        /// </summary>
        internal static string Amphora_Plant {
            get {
                return ResourceManager.GetString("Amphora Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquamarine.
        /// </summary>
        internal static string Aquamarine {
            get {
                return ResourceManager.GetString("Aquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bacterium.
        /// </summary>
        internal static string Bacterium {
            get {
                return ResourceManager.GetString("Bacterium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bark Mounds.
        /// </summary>
        internal static string Bark_Mounds {
            get {
                return ResourceManager.GetString("Bark Mounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brain Trees.
        /// </summary>
        internal static string Brain_Trees {
            get {
                return ResourceManager.GetString("Brain Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cactoida.
        /// </summary>
        internal static string Cactoida {
            get {
                return ResourceManager.GetString("Cactoida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clypeus.
        /// </summary>
        internal static string Clypeus {
            get {
                return ResourceManager.GetString("Clypeus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobalt.
        /// </summary>
        internal static string Cobalt {
            get {
                return ResourceManager.GetString("Cobalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concha.
        /// </summary>
        internal static string Concha {
            get {
                return ResourceManager.GetString("Concha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystalline Shards.
        /// </summary>
        internal static string Crystalline_Shards {
            get {
                return ResourceManager.GetString("Crystalline Shards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        internal static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricae.
        /// </summary>
        internal static string Electricae {
            get {
                return ResourceManager.GetString("Electricae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerald.
        /// </summary>
        internal static string Emerald {
            get {
                return ResourceManager.GetString("Emerald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonticulua.
        /// </summary>
        internal static string Fonticulua {
            get {
                return ResourceManager.GetString("Fonticulua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frutexa.
        /// </summary>
        internal static string Frutexa {
            get {
                return ResourceManager.GetString("Frutexa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fumerola.
        /// </summary>
        internal static string Fumerola {
            get {
                return ResourceManager.GetString("Fumerola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fungoida.
        /// </summary>
        internal static string Fungoida {
            get {
                return ResourceManager.GetString("Fungoida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        internal static string Grey {
            get {
                return ResourceManager.GetString("Grey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        internal static string Indigo {
            get {
                return ResourceManager.GetString("Indigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime.
        /// </summary>
        internal static string Lime {
            get {
                return ResourceManager.GetString("Lime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luteolum Anemone.
        /// </summary>
        internal static string Luteolum_Anemone {
            get {
                return ResourceManager.GetString("Luteolum Anemone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        internal static string Magenta {
            get {
                return ResourceManager.GetString("Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maroon.
        /// </summary>
        internal static string Maroon {
            get {
                return ResourceManager.GetString("Maroon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauve.
        /// </summary>
        internal static string Mauve {
            get {
                return ResourceManager.GetString("Mauve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mulberry.
        /// </summary>
        internal static string Mulberry {
            get {
                return ResourceManager.GetString("Mulberry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocher.
        /// </summary>
        internal static string Ocher {
            get {
                return ResourceManager.GetString("Ocher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osseus.
        /// </summary>
        internal static string Osseus {
            get {
                return ResourceManager.GetString("Osseus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peach.
        /// </summary>
        internal static string Peach {
            get {
                return ResourceManager.GetString("Peach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepta.
        /// </summary>
        internal static string Recepta {
            get {
                return ResourceManager.GetString("Recepta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage.
        /// </summary>
        internal static string Sage {
            get {
                return ResourceManager.GetString("Sage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinuous Tubers.
        /// </summary>
        internal static string Sinuous_Tubers {
            get {
                return ResourceManager.GetString("Sinuous Tubers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stratum.
        /// </summary>
        internal static string Stratum {
            get {
                return ResourceManager.GetString("Stratum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        internal static string Teal {
            get {
                return ResourceManager.GetString("Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tubus.
        /// </summary>
        internal static string Tubus {
            get {
                return ResourceManager.GetString("Tubus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise.
        /// </summary>
        internal static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tussock.
        /// </summary>
        internal static string Tussock {
            get {
                return ResourceManager.GetString("Tussock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
