//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrvSurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodexShort {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodexShort() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.Properties.CodexShort", typeof(CodexShort).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ale.
        /// </summary>
        internal static string Aleoida {
            get {
                return ResourceManager.GetString("Aleoida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amp.
        /// </summary>
        internal static string Amphora_Plant {
            get {
                return ResourceManager.GetString("Amphora Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bac.
        /// </summary>
        internal static string Bacterium {
            get {
                return ResourceManager.GetString("Bacterium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bar.
        /// </summary>
        internal static string Bark_Mounds {
            get {
                return ResourceManager.GetString("Bark Mounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bra.
        /// </summary>
        internal static string Brain_Trees {
            get {
                return ResourceManager.GetString("Brain Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cac.
        /// </summary>
        internal static string Cactoida {
            get {
                return ResourceManager.GetString("Cactoida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cly.
        /// </summary>
        internal static string Clypeus {
            get {
                return ResourceManager.GetString("Clypeus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con.
        /// </summary>
        internal static string Concha {
            get {
                return ResourceManager.GetString("Concha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cry.
        /// </summary>
        internal static string Crystalline_Shards {
            get {
                return ResourceManager.GetString("Crystalline Shards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ele.
        /// </summary>
        internal static string Electricae {
            get {
                return ResourceManager.GetString("Electricae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fon.
        /// </summary>
        internal static string Fonticulua {
            get {
                return ResourceManager.GetString("Fonticulua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fru.
        /// </summary>
        internal static string Frutexa {
            get {
                return ResourceManager.GetString("Frutexa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fum.
        /// </summary>
        internal static string Fumerola {
            get {
                return ResourceManager.GetString("Fumerola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fun.
        /// </summary>
        internal static string Fungoida {
            get {
                return ResourceManager.GetString("Fungoida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ane.
        /// </summary>
        internal static string Luteolum_Anemone {
            get {
                return ResourceManager.GetString("Luteolum Anemone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oss.
        /// </summary>
        internal static string Osseus {
            get {
                return ResourceManager.GetString("Osseus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec.
        /// </summary>
        internal static string Recepta {
            get {
                return ResourceManager.GetString("Recepta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sin.
        /// </summary>
        internal static string Sinuous_Tubers {
            get {
                return ResourceManager.GetString("Sinuous Tubers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to str.
        /// </summary>
        internal static string Stratum {
            get {
                return ResourceManager.GetString("Stratum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tub.
        /// </summary>
        internal static string Tubus {
            get {
                return ResourceManager.GetString("Tubus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tus.
        /// </summary>
        internal static string Tussock {
            get {
                return ResourceManager.GetString("Tussock", resourceCulture);
            }
        }
    }
}
