//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrvSurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommodityCategories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommodityCategories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.Properties.CommodityCategories", typeof(CommodityCategories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemicals.
        /// </summary>
        internal static string Chemicals {
            get {
                return ResourceManager.GetString("Chemicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Items.
        /// </summary>
        internal static string ConsumerItems {
            get {
                return ResourceManager.GetString("ConsumerItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foods.
        /// </summary>
        internal static string Foods {
            get {
                return ResourceManager.GetString("Foods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial Materials.
        /// </summary>
        internal static string IndustrialMaterials {
            get {
                return ResourceManager.GetString("IndustrialMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machinery.
        /// </summary>
        internal static string Machinery {
            get {
                return ResourceManager.GetString("Machinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicines.
        /// </summary>
        internal static string Medicines {
            get {
                return ResourceManager.GetString("Medicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metals.
        /// </summary>
        internal static string Metals {
            get {
                return ResourceManager.GetString("Metals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minerals.
        /// </summary>
        internal static string Minerals {
            get {
                return ResourceManager.GetString("Minerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narcotics.
        /// </summary>
        internal static string Narcotics {
            get {
                return ResourceManager.GetString("Narcotics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-marketable.
        /// </summary>
        internal static string NonMarketable {
            get {
                return ResourceManager.GetString("NonMarketable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerplay.
        /// </summary>
        internal static string Powerplay {
            get {
                return ResourceManager.GetString("Powerplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvage.
        /// </summary>
        internal static string Salvage {
            get {
                return ResourceManager.GetString("Salvage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        internal static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textiles.
        /// </summary>
        internal static string Textiles {
            get {
                return ResourceManager.GetString("Textiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste.
        /// </summary>
        internal static string Waste {
            get {
                return ResourceManager.GetString("Waste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        internal static string Weapons {
            get {
                return ResourceManager.GetString("Weapons", resourceCulture);
            }
        }
    }
}
