//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrvSurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Economies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Economies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.Properties.Economies", typeof(Economies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture.
        /// </summary>
        internal static string Agri {
            get {
                return ResourceManager.GetString("Agri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Enterprise.
        /// </summary>
        internal static string Carrier {
            get {
                return ResourceManager.GetString("Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colony.
        /// </summary>
        internal static string Colony {
            get {
                return ResourceManager.GetString("Colony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaged.
        /// </summary>
        internal static string Damaged {
            get {
                return ResourceManager.GetString("Damaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering.
        /// </summary>
        internal static string Engineer {
            get {
                return ResourceManager.GetString("Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction.
        /// </summary>
        internal static string Extraction {
            get {
                return ResourceManager.GetString("Extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Tech.
        /// </summary>
        internal static string HighTech {
            get {
                return ResourceManager.GetString("HighTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial.
        /// </summary>
        internal static string Industrial {
            get {
                return ResourceManager.GetString("Industrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military.
        /// </summary>
        internal static string Military {
            get {
                return ResourceManager.GetString("Military", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison.
        /// </summary>
        internal static string Prison {
            get {
                return ResourceManager.GetString("Prison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refinery.
        /// </summary>
        internal static string Refinery {
            get {
                return ResourceManager.GetString("Refinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescue.
        /// </summary>
        internal static string Rescue {
            get {
                return ResourceManager.GetString("Rescue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terraforming.
        /// </summary>
        internal static string Terraforming {
            get {
                return ResourceManager.GetString("Terraforming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourism.
        /// </summary>
        internal static string Tourism {
            get {
                return ResourceManager.GetString("Tourism", resourceCulture);
            }
        }
    }
}
