//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrvSurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FactionStates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FactionStates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.Properties.FactionStates", typeof(FactionStates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blight.
        /// </summary>
        internal static string Blight {
            get {
                return ResourceManager.GetString("Blight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boom.
        /// </summary>
        internal static string Boom {
            get {
                return ResourceManager.GetString("Boom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust.
        /// </summary>
        internal static string Bust {
            get {
                return ResourceManager.GetString("Bust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Liberty.
        /// </summary>
        internal static string CivilLiberty {
            get {
                return ResourceManager.GetString("CivilLiberty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Unrest.
        /// </summary>
        internal static string CivilUnrest {
            get {
                return ResourceManager.GetString("CivilUnrest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil War.
        /// </summary>
        internal static string CivilWar {
            get {
                return ResourceManager.GetString("CivilWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold War.
        /// </summary>
        internal static string ColdWar {
            get {
                return ResourceManager.GetString("ColdWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonisation.
        /// </summary>
        internal static string Colonisation {
            get {
                return ResourceManager.GetString("Colonisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drought.
        /// </summary>
        internal static string Drought {
            get {
                return ResourceManager.GetString("Drought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Election.
        /// </summary>
        internal static string Election {
            get {
                return ResourceManager.GetString("Election", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion.
        /// </summary>
        internal static string Expansion {
            get {
                return ResourceManager.GetString("Expansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famine.
        /// </summary>
        internal static string Famine {
            get {
                return ResourceManager.GetString("Famine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historic Event.
        /// </summary>
        internal static string HistoricEvent {
            get {
                return ResourceManager.GetString("HistoricEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incursion.
        /// </summary>
        internal static string Incursion {
            get {
                return ResourceManager.GetString("Incursion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure Failure.
        /// </summary>
        internal static string InfrastructureFailure {
            get {
                return ResourceManager.GetString("InfrastructureFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment.
        /// </summary>
        internal static string Investment {
            get {
                return ResourceManager.GetString("Investment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockdown.
        /// </summary>
        internal static string Lockdown {
            get {
                return ResourceManager.GetString("Lockdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Disaster.
        /// </summary>
        internal static string NaturalDisaster {
            get {
                return ResourceManager.GetString("NaturalDisaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbreak.
        /// </summary>
        internal static string Outbreak {
            get {
                return ResourceManager.GetString("Outbreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirate Attack.
        /// </summary>
        internal static string PirateAttack {
            get {
                return ResourceManager.GetString("PirateAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Holiday.
        /// </summary>
        internal static string PublicHoliday {
            get {
                return ResourceManager.GetString("PublicHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retreat.
        /// </summary>
        internal static string Retreat {
            get {
                return ResourceManager.GetString("Retreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolution.
        /// </summary>
        internal static string Revolution {
            get {
                return ResourceManager.GetString("Revolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technological Leap.
        /// </summary>
        internal static string TechnologicalLeap {
            get {
                return ResourceManager.GetString("TechnologicalLeap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorism.
        /// </summary>
        internal static string Terrorism {
            get {
                return ResourceManager.GetString("Terrorism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thargoid Controlled.
        /// </summary>
        internal static string Thargoid_Controlled {
            get {
                return ResourceManager.GetString("Thargoid_Controlled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thargoid Invasion.
        /// </summary>
        internal static string Thargoid_Harvest {
            get {
                return ResourceManager.GetString("Thargoid_Harvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thargoid Alert.
        /// </summary>
        internal static string Thargoid_Probing {
            get {
                return ResourceManager.GetString("Thargoid_Probing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Thargoid Recovery.
        /// </summary>
        internal static string Thargoid_Recovery {
            get {
                return ResourceManager.GetString("Thargoid_Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thargoid Maelstrom.
        /// </summary>
        internal static string Thargoid_Stronghold {
            get {
                return ResourceManager.GetString("Thargoid_Stronghold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade War.
        /// </summary>
        internal static string TradeWar {
            get {
                return ResourceManager.GetString("TradeWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War.
        /// </summary>
        internal static string War {
            get {
                return ResourceManager.GetString("War", resourceCulture);
            }
        }
    }
}
