//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrvSurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormRouteExtras {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormRouteExtras() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.Properties.FormRouteExtras", typeof(FormRouteExtras).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrived at hop #{0} {1}.
        /// </summary>
        internal static string ArrivedAt {
            get {
                return ResourceManager.GetString("ArrivedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto copy in Gal-Map.
        /// </summary>
        internal static string AutoCopyButton {
            get {
                return ResourceManager.GetString("AutoCopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} systems.
        /// </summary>
        internal static string ImportedSystems {
            get {
                return ResourceManager.GetString("ImportedSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Spansh route: &apos;{0}&apos; ....
        /// </summary>
        internal static string ImportingSpansh {
            get {
                return ResourceManager.GetString("ImportingSpansh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing ~{0} names....
        /// </summary>
        internal static string ImportNames {
            get {
                return ResourceManager.GetString("ImportNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To proceed: copy a number of system names to the clipboard, one system per line..
        /// </summary>
        internal static string MsgNamesClipboard {
            get {
                return ResourceManager.GetString("MsgNamesClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To proceed: copy the URL of any Spansh route to the clipboard.
        /// </summary>
        internal static string MsgSpanshClipboard {
            get {
                return ResourceManager.GetString("MsgSpanshClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutron.
        /// </summary>
        internal static string Neutron {
            get {
                return ResourceManager.GetString("Neutron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose import file.
        /// </summary>
        internal static string OpenTextFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenTextFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuel.
        /// </summary>
        internal static string Refuel {
            get {
                return ResourceManager.GetString("Refuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route active.
        /// </summary>
        internal static string RouteActiveButton {
            get {
                return ResourceManager.GetString("RouteActiveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route complete.
        /// </summary>
        internal static string RouteComplete {
            get {
                return ResourceManager.GetString("RouteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route not found: {0}.
        /// </summary>
        internal static string RouteNotFound {
            get {
                return ResourceManager.GetString("RouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route not started.
        /// </summary>
        internal static string RouteNotStarted {
            get {
                return ResourceManager.GetString("RouteNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route progress: #{0} of {1}.
        /// </summary>
        internal static string RouteProgress {
            get {
                return ResourceManager.GetString("RouteProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported {0} hops.
        /// </summary>
        internal static string SpanshImportSuccess {
            get {
                return ResourceManager.GetString("SpanshImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files.
        /// </summary>
        internal static string TextFiles {
            get {
                return ResourceManager.GetString("TextFiles", resourceCulture);
            }
        }
    }
}
