//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrvSurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Guardian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Guardian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.Properties.Guardian", typeof(Guardian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter.
        /// </summary>
        internal static string BluePrintFighter {
            get {
                return ResourceManager.GetString("BluePrintFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string BluePrintModule {
            get {
                return ResourceManager.GetString("BluePrintModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        internal static string BluePrintWeapon {
            get {
                return ResourceManager.GetString("BluePrintWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma.
        /// </summary>
        internal static string Gamma {
            get {
                return ResourceManager.GetString("Gamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basilisk.
        /// </summary>
        internal static string ItemBasilisk {
            get {
                return ResourceManager.GetString("ItemBasilisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casket.
        /// </summary>
        internal static string ItemCasket {
            get {
                return ResourceManager.GetString("ItemCasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclops.
        /// </summary>
        internal static string ItemCyclops {
            get {
                return ResourceManager.GetString("ItemCyclops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string ItemLink {
            get {
                return ResourceManager.GetString("ItemLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medusa.
        /// </summary>
        internal static string ItemMedusa {
            get {
                return ResourceManager.GetString("ItemMedusa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb.
        /// </summary>
        internal static string ItemOrb {
            get {
                return ResourceManager.GetString("ItemOrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe.
        /// </summary>
        internal static string ItemProbe {
            get {
                return ResourceManager.GetString("ItemProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relic.
        /// </summary>
        internal static string ItemRelic {
            get {
                return ResourceManager.GetString("ItemRelic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        internal static string ItemSensor {
            get {
                return ResourceManager.GetString("ItemSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablet.
        /// </summary>
        internal static string ItemTablet {
            get {
                return ResourceManager.GetString("ItemTablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totem.
        /// </summary>
        internal static string ItemTotem {
            get {
                return ResourceManager.GetString("ItemTotem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urn.
        /// </summary>
        internal static string ItemUrn {
            get {
                return ResourceManager.GetString("ItemUrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biology.
        /// </summary>
        internal static string LogBiology {
            get {
                return ResourceManager.GetString("LogBiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string LogCulture {
            get {
                return ResourceManager.GetString("LogCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string LogHistory {
            get {
                return ResourceManager.GetString("LogHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LogLanguage {
            get {
                return ResourceManager.GetString("LogLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        internal static string LogTechnology {
            get {
                return ResourceManager.GetString("LogTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component tower.
        /// </summary>
        internal static string POIType_Component {
            get {
                return ResourceManager.GetString("POIType_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pylon.
        /// </summary>
        internal static string POIType_Pylon {
            get {
                return ResourceManager.GetString("POIType_Pylon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruins.
        /// </summary>
        internal static string Ruins {
            get {
                return ResourceManager.GetString("Ruins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absent.
        /// </summary>
        internal static string SitePoiStatus_absent {
            get {
                return ResourceManager.GetString("SitePoiStatus_absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        internal static string SitePoiStatus_empty {
            get {
                return ResourceManager.GetString("SitePoiStatus_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to present.
        /// </summary>
        internal static string SitePoiStatus_present {
            get {
                return ResourceManager.GetString("SitePoiStatus_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string SitePoiStatus_unknown {
            get {
                return ResourceManager.GetString("SitePoiStatus_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure.
        /// </summary>
        internal static string Structure {
            get {
                return ResourceManager.GetString("Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
