//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrvSurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyChords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyChords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.Properties.KeyChords", typeof(KeyChords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In gal-map, copy the next boxel search system to clipboard..
        /// </summary>
        internal static string copyNextBoxel {
            get {
                return ResourceManager.GetString("copyNextBoxel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles making the map fill half the screen, at Human settlements only..
        /// </summary>
        internal static string mapBeHuge {
            get {
                return ResourceManager.GetString("mapBeHuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the zoom to default, at Human and Guardian sites..
        /// </summary>
        internal static string mapZoomAuto {
            get {
                return ResourceManager.GetString("mapZoomAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in on maps at Human and Guardian sites..
        /// </summary>
        internal static string mapZoomIn {
            get {
                return ResourceManager.GetString("mapZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out on maps at Human and Guardian sites..
        /// </summary>
        internal static string mapZoomOut {
            get {
                return ResourceManager.GetString("mapZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force show the Body info overlay..
        /// </summary>
        internal static string showBodyInfo {
            get {
                return ResourceManager.GetString("showBodyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force show the FSS info overlay..
        /// </summary>
        internal static string showFssInfo {
            get {
                return ResourceManager.GetString("showFssInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force toggle the FSD jump overlay to be visible without starting to jump. Will not appear if there is no active route..
        /// </summary>
        internal static string showJumpInfo {
            get {
                return ResourceManager.GetString("showJumpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles visibility of all overlay windows..
        /// </summary>
        internal static string toggleAllVisibility {
            get {
                return ResourceManager.GetString("toggleAllVisibility", resourceCulture);
            }
        }
    }
}
