//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrvSurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyChords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyChords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.Properties.KeyChords", typeof(KeyChords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle collapsing cargo groups when enough on FCs..
        /// </summary>
        internal static string collapseColonyData {
            get {
                return ResourceManager.GetString("collapseColonyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In gal-map, copy the next boxel search system to clipboard..
        /// </summary>
        internal static string copyNextBoxel {
            get {
                return ResourceManager.GetString("copyNextBoxel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles making the map fill half the screen, at Human settlements only..
        /// </summary>
        internal static string mapBeHuge {
            get {
                return ResourceManager.GetString("mapBeHuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the zoom to default, at Human and Guardian sites..
        /// </summary>
        internal static string mapZoomAuto {
            get {
                return ResourceManager.GetString("mapZoomAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in on maps at Human and Guardian sites..
        /// </summary>
        internal static string mapZoomIn {
            get {
                return ResourceManager.GetString("mapZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out on maps at Human and Guardian sites..
        /// </summary>
        internal static string mapZoomOut {
            get {
                return ResourceManager.GetString("mapZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set focus on a different game window..
        /// </summary>
        internal static string nextWindow {
            get {
                return ResourceManager.GetString("nextWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste clipboard text when in Gal-Map.
        /// </summary>
        internal static string pasteGalMap {
            get {
                return ResourceManager.GetString("pasteGalMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately refresh of Colonisation data..
        /// </summary>
        internal static string refreshColonyData {
            get {
                return ResourceManager.GetString("refreshColonyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force show the Body info overlay..
        /// </summary>
        internal static string showBodyInfo {
            get {
                return ResourceManager.GetString("showBodyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force show the Colonisation shopping list overlay..
        /// </summary>
        internal static string showColonyShopping {
            get {
                return ResourceManager.GetString("showColonyShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force show the FSS info overlay..
        /// </summary>
        internal static string showFssInfo {
            get {
                return ResourceManager.GetString("showFssInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force toggle the FSD jump overlay without starting to jump..
        /// </summary>
        internal static string showJumpInfo {
            get {
                return ResourceManager.GetString("showJumpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force show the Station Info overlay..
        /// </summary>
        internal static string showStationInfo {
            get {
                return ResourceManager.GetString("showStationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the system notes window visible..
        /// </summary>
        internal static string showSystemNotes {
            get {
                return ResourceManager.GetString("showSystemNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles visibility of all overlay windows..
        /// </summary>
        internal static string toggleAllVisibility {
            get {
                return ResourceManager.GetString("toggleAllVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove tracker #1.
        /// </summary>
        internal static string track1 {
            get {
                return ResourceManager.GetString("track1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove tracker #2.
        /// </summary>
        internal static string track2 {
            get {
                return ResourceManager.GetString("track2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove tracker #3.
        /// </summary>
        internal static string track3 {
            get {
                return ResourceManager.GetString("track3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove tracker #4.
        /// </summary>
        internal static string track4 {
            get {
                return ResourceManager.GetString("track4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove tracker #5.
        /// </summary>
        internal static string track5 {
            get {
                return ResourceManager.GetString("track5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove tracker #6.
        /// </summary>
        internal static string track6 {
            get {
                return ResourceManager.GetString("track6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove tracker #7.
        /// </summary>
        internal static string track7 {
            get {
                return ResourceManager.GetString("track7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove tracker #8.
        /// </summary>
        internal static string track8 {
            get {
                return ResourceManager.GetString("track8", resourceCulture);
            }
        }
    }
}
