//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrvSurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Misc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Misc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.Properties.Misc", typeof(Misc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string FormBoxelSearch_Activate {
            get {
                return ResourceManager.GetString("FormBoxelSearch_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string FormBoxelSearch_Disable {
            get {
                return ResourceManager.GetString("FormBoxelSearch_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏶ Hide list.
        /// </summary>
        internal static string FormBoxelSearch_HideList {
            get {
                return ResourceManager.GetString("FormBoxelSearch_HideList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a boxel generated system name..
        /// </summary>
        internal static string FormBoxelSearch_NotViableMessage {
            get {
                return ResourceManager.GetString("FormBoxelSearch_NotViableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxel search is not active..
        /// </summary>
        internal static string FormBoxelSearch_SearchNotActive {
            get {
                return ResourceManager.GetString("FormBoxelSearch_SearchNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏷ Show list.
        /// </summary>
        internal static string FormBoxelSearch_ShowList {
            get {
                return ResourceManager.GetString("FormBoxelSearch_ShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spansh updated: {0}.
        /// </summary>
        internal static string FormBoxelSearch_SpanshUpdated {
            get {
                return ResourceManager.GetString("FormBoxelSearch_SpanshUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spansh updated: {0}, bodies: {1}.
        /// </summary>
        internal static string FormBoxelSearch_SpanshUpdatedBodies {
            get {
                return ResourceManager.GetString("FormBoxelSearch_SpanshUpdatedBodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undiscovered system.
        /// </summary>
        internal static string FormBoxelSearch_UndiscoveredSystem {
            get {
                return ResourceManager.GetString("FormBoxelSearch_UndiscoveredSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited: {0}.
        /// </summary>
        internal static string FormBoxelSearch_Visited {
            get {
                return ResourceManager.GetString("FormBoxelSearch_Visited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed {2} of {3} boxels, {0} of {1} systems in current boxel.
        /// </summary>
        internal static string FormBoxelSearch_VisitedCounts {
            get {
                return ResourceManager.GetString("FormBoxelSearch_VisitedCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodies.
        /// </summary>
        internal static string NetSysData_Bodies {
            get {
                return ResourceManager.GetString("NetSysData_Bodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered, {0} bodies.
        /// </summary>
        internal static string NetSysData_DiscoveredAll {
            get {
                return ResourceManager.GetString("NetSysData_DiscoveredAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered ({0} of {1}).
        /// </summary>
        internal static string NetSysData_DiscoveredPartial {
            get {
                return ResourceManager.GetString("NetSysData_DiscoveredPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Encoded).
        /// </summary>
        internal static string NetSysData_Encoded {
            get {
                return ResourceManager.GetString("NetSysData_Encoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Engineer).
        /// </summary>
        internal static string NetSysData_Engineer {
            get {
                return ResourceManager.GetString("NetSysData_Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC.
        /// </summary>
        internal static string NetSysData_FC {
            get {
                return ResourceManager.GetString("NetSysData_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genus.
        /// </summary>
        internal static string NetSysData_Genus {
            get {
                return ResourceManager.GetString("NetSysData_Genus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guardian).
        /// </summary>
        internal static string NetSysData_GuardianBroker {
            get {
                return ResourceManager.GetString("NetSysData_GuardianBroker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Human).
        /// </summary>
        internal static string NetSysData_HumanBroker {
            get {
                return ResourceManager.GetString("NetSysData_HumanBroker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Manufactured).
        /// </summary>
        internal static string NetSysData_Manufactured {
            get {
                return ResourceManager.GetString("NetSysData_Manufactured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Trader.
        /// </summary>
        internal static string NetSysData_MaterialTrader {
            get {
                return ResourceManager.GetString("NetSysData_MaterialTrader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outposts.
        /// </summary>
        internal static string NetSysData_Outposts {
            get {
                return ResourceManager.GetString("NetSysData_Outposts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Raw).
        /// </summary>
        internal static string NetSysData_Raw {
            get {
                return ResourceManager.GetString("NetSysData_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlements.
        /// </summary>
        internal static string NetSysData_Settlements {
            get {
                return ResourceManager.GetString("NetSysData_Settlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star ports.
        /// </summary>
        internal static string NetSysData_StarPorts {
            get {
                return ResourceManager.GetString("NetSysData_StarPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech Broker.
        /// </summary>
        internal static string NetSysData_TechBroker {
            get {
                return ResourceManager.GetString("NetSysData_TechBroker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undiscovered system.
        /// </summary>
        internal static string NetSysData_UndiscoveredSystem {
            get {
                return ResourceManager.GetString("NetSysData_UndiscoveredSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unscanned system.
        /// </summary>
        internal static string NetSysData_UnscannedSystem {
            get {
                return ResourceManager.GetString("NetSysData_UnscannedSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wars.
        /// </summary>
        internal static string NetSysData_Wars {
            get {
                return ResourceManager.GetString("NetSysData_Wars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Surface gravity {0}g.
        /// </summary>
        internal static string PlotFlightWarning_SurfaceGravityWarning {
            get {
                return ResourceManager.GetString("PlotFlightWarning_SurfaceGravityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}x Genus.
        /// </summary>
        internal static string PlotGalMap_CountGenus {
            get {
                return ResourceManager.GetString("PlotGalMap_CountGenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current:.
        /// </summary>
        internal static string PlotGalMap_Current {
            get {
                return ResourceManager.GetString("PlotGalMap_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from: EDSM + Spansh + Canonn.
        /// </summary>
        internal static string PlotGalMap_DataFrom {
            get {
                return ResourceManager.GetString("PlotGalMap_DataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination:.
        /// </summary>
        internal static string PlotGalMap_Destination {
            get {
                return ResourceManager.GetString("PlotGalMap_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By {0}, {1}.
        /// </summary>
        internal static string PlotGalMap_DiscoveredBy {
            get {
                return ResourceManager.GetString("PlotGalMap_DiscoveredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated: {0}.
        /// </summary>
        internal static string PlotGalMap_LastUpdated {
            get {
                return ResourceManager.GetString("PlotGalMap_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next jump:.
        /// </summary>
        internal static string PlotGalMap_NextJump {
            get {
                return ResourceManager.GetString("PlotGalMap_NextJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No route set.
        /// </summary>
        internal static string PlotGalMap_NoRouteSet {
            get {
                return ResourceManager.GetString("PlotGalMap_NoRouteSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: ► {0} jumps ► Distance: {1} ly.
        /// </summary>
        internal static string PlotGalMap_RouteFooter {
            get {
                return ResourceManager.GetString("PlotGalMap_RouteFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected:.
        /// </summary>
        internal static string PlotGalMap_Selected {
            get {
                return ResourceManager.GetString("PlotGalMap_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | {0}x Bio signals on: .
        /// </summary>
        internal static string PlotSysStatus_BioSignals {
            get {
                return ResourceManager.GetString("PlotSysStatus_BioSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}x bodies: .
        /// </summary>
        internal static string PlotSysStatus_DssRemaining {
            get {
                return ResourceManager.GetString("PlotSysStatus_DssRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSS {0}% complete.
        /// </summary>
        internal static string PlotSysStatus_FssCompleteLong {
            get {
                return ResourceManager.GetString("PlotSysStatus_FssCompleteLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSS {0}%.
        /// </summary>
        internal static string PlotSysStatus_FssCompleteShort {
            get {
                return ResourceManager.GetString("PlotSysStatus_FssCompleteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSS not started.
        /// </summary>
        internal static string PlotSysStatus_FssNotStarted {
            get {
                return ResourceManager.GetString("PlotSysStatus_FssNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSS survey: .
        /// </summary>
        internal static string PlotSysStatus_Header {
            get {
                return ResourceManager.GetString("PlotSysStatus_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next system:.
        /// </summary>
        internal static string PlotSysStatus_NextSystem {
            get {
                return ResourceManager.GetString("PlotSysStatus_NextSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string PlotSysStatus_NoDssMeet {
            get {
                return ResourceManager.GetString("PlotSysStatus_NoDssMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ► {0} non-body signals.
        /// </summary>
        internal static string PlotSysStatus_NonBodySignals {
            get {
                return ResourceManager.GetString("PlotSysStatus_NonBodySignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find folder:
        ///{0}
        ///
        ///Would you like to create it?.
        /// </summary>
        internal static string Settings_CreateFolderNotFound {
            get {
                return ResourceManager.GetString("Settings_CreateFolderNotFound", resourceCulture);
            }
        }
    }
}
