//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrvSurvey.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Plotters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Plotters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvSurvey.Resources.Plotters", typeof(Plotters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Surface gravity {0}g.
        /// </summary>
        public static string PlotFlightWarning_SurfaceGravityWarning {
            get {
                return ResourceManager.GetString("PlotFlightWarning_SurfaceGravityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from: EDSM + Spansh + Canonn.
        /// </summary>
        public static string PlotGalMap_DataFrom {
            get {
                return ResourceManager.GetString("PlotGalMap_DataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No route set.
        /// </summary>
        public static string PlotGalMap_NoRouteSet {
            get {
                return ResourceManager.GetString("PlotGalMap_NoRouteSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: ► {0} jumps ► Distance: {1} ly.
        /// </summary>
        public static string PlotGalMap_RouteFooter {
            get {
                return ResourceManager.GetString("PlotGalMap_RouteFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | {0}x Bio signals on: .
        /// </summary>
        public static string PlotSysStatus_BioSignals {
            get {
                return ResourceManager.GetString("PlotSysStatus_BioSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}x bodies: .
        /// </summary>
        public static string PlotSysStatus_DssRemaining {
            get {
                return ResourceManager.GetString("PlotSysStatus_DssRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSS {0}%.
        /// </summary>
        public static string PlotSysStatus_FssCompleteLong {
            get {
                return ResourceManager.GetString("PlotSysStatus_FssCompleteLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSS {0}% complete.
        /// </summary>
        public static string PlotSysStatus_FssCompleteShort {
            get {
                return ResourceManager.GetString("PlotSysStatus_FssCompleteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSS not started.
        /// </summary>
        public static string PlotSysStatus_FssNotStarted {
            get {
                return ResourceManager.GetString("PlotSysStatus_FssNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System survey: .
        /// </summary>
        public static string PlotSysStatus_Header {
            get {
                return ResourceManager.GetString("PlotSysStatus_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next system:.
        /// </summary>
        public static string PlotSysStatus_NextSystem {
            get {
                return ResourceManager.GetString("PlotSysStatus_NextSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DSS meet criteria.
        /// </summary>
        public static string PlotSysStatus_NoDssMeet {
            get {
                return ResourceManager.GetString("PlotSysStatus_NoDssMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ► {0} non-body signals.
        /// </summary>
        public static string PlotSysStatus_NonBodySignals {
            get {
                return ResourceManager.GetString("PlotSysStatus_NonBodySignals", resourceCulture);
            }
        }
    }
}
